/*
 * ============================================================================
 * = COPYRIGHT
 *          PAX Computer Technology(Shenzhen) Co., Ltd. PROPRIETARY INFORMATION
 *   This software is supplied under the terms of a license agreement or nondisclosure
 *   agreement with PAX Computer Technology(Shenzhen) Co., Ltd. and may not be copied or
 *   disclosed except in accordance with the terms in that agreement.
 *     Copyright (C) 2023 PAX Computer Technology(Shenzhen) Co., Ltd. All rights reserved.
 * ============================================================================
 */

#ifndef POSLinkErrorMsg_h
#define POSLinkErrorMsg_h

#define PROCESS_TRANS_RESULT_MSG "ProcessTransResult Msg: "
//EMSG = Error Message
#define SUCC "SUCC"
//Pack Error
#define PACK_ERROR_REQUEST_NOT_SET @"POSLINK PACK ERROR: REQUEST NOT SET"
#define PACK_ERROR_TENDER_TYPE_NOT_SET @"POSLINK PACK ERROR: TENDER TYPE NOT SET"
#define PACK_ERROR_TRANS_TYPE_NOT_SET @"POSLINK PACK ERROR: TRANS TYPE NOT SET"
#define PACK_ERROR_TENDER_TYPE_INVALID @"POSLINK PACK ERROR: TENDER TYPE INVALID"
#define PACK_ERROR_TRANS_TYPE_INVALID @"POSLINK PACK ERROR: TRANS TYPE INVALID"
#define PACK_ERROR_UNKOW_REQUEST @"POSLINK PACK ERROR: UNKNOW REQUEST"
//Commsetting Error
#define COMMSETTING_ERROR_COMM_TYPE_INVALID @"POSLINK COMMSETTING ERROR: COMM TYPE INVALID"
#define COMMSETTING_ERROR_TIMEOUT_INVALID @"POSLINK COMMSETTING ERROR: TIMEOUT INVALID"
#define COMMSETTING_ERROR_DEST_IP_INVALID @"POSLINK COMMSETTING ERROR: DEST IP INVALID"
#define COMMSETTING_ERROR_DEST_PORT_INVALID @"POSLINK COMMSETTING ERROR: DEST PORT INVALID"
#define COMMSETTING_ERROR_BLUETOOTH_ADRESSS_INVALID @"POSLINK COMMSETTING ERROR: BLUETOOTH ADRESSS INVALID"
//Communication Error
#define COMMUNICATION_ERROR_CONNECT_ERROR @"POSLINK COMMUNICATION ERROR: CONNECT ERROR"
#define COMMUNICATION_ERROR_SEND_DATA_ERROR @"POSLINK COMMUNICATION ERROR: SEND DATA ERROR"
#define COMMUNICATION_ERROR_RECV_DATA_ERROR @"POSLINK COMMUNICATION ERROR: RECV DATA ERROR"
//Transaction Error
#define TRANSACTION_ERROR_SEND_DATA_RECV_ACK_ERROR @"POSLINK TRANSACTION ERROR: SEND DATA RECV ACK ERROR"
#define TRANSACTION_ERROR_RECEIVED_EOT_RATHER_THAN_RESPONSE @"POSLINK TRANSACTION ERROR: RECEIVED EOT RATHER THAN RESPONSE"
#define TRANSACTION_ERROR_LRC_ERROR @"POSLINK TRANSACTION ERROR: LRC ERROR"
//Timeout
#define TIMEOUT_RECV_DATA_TIMEOUT @"POSLINK TIMEOUT: RECV DATA TIMEOUT"
#define TIMEOUT_SEND_DATA_RECV_ACK_TIMEOUT @"POSLINK TIMEOUT: SEND DATA RECV ACK TIMEOUT"
//Unpack Error
#define UNPACK_ERROR @"POSLINK UNPACK ERROR"
//Unknown Error
#define UNKNOWN_ERROR @"POSLINK UNKNOWN ERROR"
//session end
#define SESSION_END @"POSLINK SESSION END"
//Protocol error
#define PROTOCOL_ERROR_UNSOPPORT_ERROR @"PROTOCOL UNKNOWN ERROR: UNKNOWN PROTOCOL TYPE"

#endif /* POSLinkErrorMsg_h */
